// components/card/Background.vue
<template>
  <div
    class="card ultra-radius card-background flex-1 view-anchor gradient-mask mb-4"
    :class="[isDarkTheme ? 'hover-card-neon-yellow' : ' hover-card-crimson']"
    style=""
    @mouseover="isHover = true"
    @mouseout="isHover = false"
  >
    <img
      :src="article.cover ? article.cover : article.imageHeader"
      class="card-background-image hover-filter-cyberpunk-v"
      alt="teste"
    />
    <div class="mask texture-mask-4"></div>
    <div
      class="card-img-overlay h-100 d-flex flex-column justify-content-end p-4"
    >
      <!-- <div class="d-flex align-items-center mb-2">
        <span
          class="marker-line py-1 bg-dark text-light"
          style="font-weight: 500"
        >
          <DateFormat :date="article.createdDate" full />
        </span>
      </div> -->

      <h3 class="card-title">
        <span class="bg-dark text-light py-1">
          <span class="marker-line"> {{ article.title }} </span>
        </span>
      </h3>

      <div class="d-flex justify-content-between">
        <div class="d-flex align-items-center mt-1 mb-1">
          <div class="flex-shrink-0">
            <span class="visually-hidden-focusable">{{
              article.author.name
            }}</span>
            <img
              class="rounded-circle border border-dark"
              src="https://i.imgur.com/h4BIIOc.jpg"
              alt=""
              style="height: 48px; width: 48px; object-fit: cover"
            />
          </div>
          <div class="ms-2">
            <p class="text-sm font-medium text-light mb-0">
              <span class="marker-line bg-dark custom-padding">
                {{ article.author.name }}
              </span>
            </p>
            <div class="flex space-x-1 text-sm text-light">
              <time
                class="marker-line bg-dark text-capitalize custom-padding"
                dateTime="article.createdDate"
              >
                <DateFormat :date="article.createdDate" />
              </time>
            </div>
          </div>
        </div>
        <div class="d-flex align-items-end">
          <div class="">
            <nuxt-link
              :to="article.path"
              class="btn btn-read-more-sm"
              :class="isDarkTheme ? 'btn-neon-yellow' : 'btn-uv'"
            >
              Ler mais...
            </nuxt-link>
          </div>
        </div>
      </div>

      <!-- <div class="d-flex align-items-center mb-2">
        <span
          class="marker-line py-1 bg-dark text-light"
          style="font-weight: 500"
        >
          Por {{ article.author.name }} em {{ article.channel }}
        </span>
      </div> -->
    </div>
  </div>
</template>
<script>
import { mapGetters } from 'vuex'
export default {
  props: {
    article: {
      type: Object,
      default: null,
    },

    articleured: {
      type: Boolean,
      default: false,
    },

    badgeIsTag: {
      type: Boolean,
      default: false,
    },

    category: {
      type: Boolean,
      default: false,
    },

    tags: {
      type: Boolean,
      default: false,
    },
  },

  data() {
    return {
      isHover: false,
    }
  },

  computed: {
    ...mapGetters(['isDarkTheme']),
  },

  methods: {
    slugName(data) {
      const link = data.replace('articles/', '').replace('/', '')
      return link
    },
  },
}
</script>
<style lang="scss">
.ultra-radius {
  border-radius: 1.25rem !important;
}

.custom-padding {
  padding: 0.125rem 0.25rem !important;
}
</style>

// components/card/background.tsx
"use client";
import * as React from "react";
import Image from "next/image";
import Link from "next/link";

import { Button } from "../ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

import { FormatDate } from "../date-format";
import { Project } from "@/types";

import { format } from "date-fns";
import { ptBR } from "date-fns/locale";
import { Badge } from "../ui/badge";

interface CardProps {
  document: Project;
  authors: any;
  isFeatured?: boolean;
}

export const CardBackground = ({
  document,
  authors,
  isFeatured = false,
}: CardProps) => {
  const fallbackImage = "/images/blklight-thumb.jpg";

  const image = (document: any) => {
    const data = document.cover
      ? document.cover
      : document.imageHeader
      ? document.imageHeader
      : fallbackImage;
    return data;
  };
  return (
    <div className="card card-background border border-dark-500 dark:border-light-500 hover:hover-card !rounded-xs hover:hover-card-dark-bordered hover:dark:hover-card-light-bordered view-anchor group">
      <img
        src={image(document)}
        className={`!rounded-xs scale-150 ${document.filter} ${
          isFeatured
            ? "card-background-image-featured"
            : "card-background-image"
        }`}
        alt={`${document.title} image`}
      />
      <div className="mask texture-mask-4"></div>
      <div className="card-img-overlay flex flex-col">
        <div className="flex items-center leading-normal !text-base">
          <span className="marker-line text-light-500 rounded-xs font-medium bg-dark-500 !py-1 text-lg tracking-wide">
            <FormatDate date={document.date} />
          </span>
        </div>
      </div>
      <div className="card-img-overlay flex flex-col justify-end">
        <h3 className="card-title text-3xl">
          <Link
            className=""
            href={`${document.slug}`}
            aria-label="Ir para o projeto"
          >
            <span className="marker-line rounded-xs bg-dark-500 text-light-500 !py-1 hover:underline underline-offset-1">
              {document.title}
            </span>
          </Link>
        </h3>

        <div className="flex mt-1">
          {authors &&
            authors.map((author: any) => (
              <div key={author.name} className="flex items-center my-1">
                <div className="shrink-0">
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <img
                          id={`anchor-${author.slug}-${document.slug}`}
                          src={author.avatar}
                          className="w-[50px] h-[50px] object-cover rounded-full border border-dark-500 mr-2"
                          alt={`${author.name} avatar`}
                        />
                      </TooltipTrigger>
                      <TooltipContent align="center" side="right">
                        <p>{author.name}</p>
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </div>
              </div>
            ))}

          <div className="flex flex-1 items-center">
            <Button className="ml-auto" asChild>
              <Link href={`${document.slug}`} aria-label="Ir para o projeto">
                Ler mais
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};
